### ISSUE TITLE
Error in Birth Date Calculations

### ISSUE THREAD

**Issue by jguzman55269** [JoelMon/Florida-License-Calculator#4]
There is an error in the calculation involving the sex. If a capital “M” is input, the result will be incorrect. see attached screenshot
![E57E6E87-D080-4E6D-B01B-348AEEA5A9E4](https://user-images.githubusercontent.com/50344685/57265976-f3fddb80-7047-11e9-8fe5-970d3d917fb8.jpeg)

**Comment by JoelMon** [comment]
Awesome, I believe the problem is line 126. Will fix it now.
